project:
  type: website
website:
  title: "WrightMap"
  site-url: "https://www.wrightmap.org"
  navbar:
    background: primary
    search: true
    left:
      - file: about.qmd
        text: About WrightMap
      - text: Tutorials      
        menu:
          - file: tutorial01.qmd
            text: Plotting Unidimensional/Dichotomous Models
          - file: tutorial02.qmd
            text: Plotting Items in Different Ways
          - file: tutorial03.qmd
            text: Plotting Multidimensional & Polytomous Models
          - file: tutorial04.qmd
            text: Using Conquest Output and Making Thresholds
          - file: tutorial05.qmd
            text: More Flexibility Using the person and item side functions                        
          # Add more tutorials here

      - text: Examples
        menu:
          - file: example01.qmd
            text: Simulating data
          - file: example02.qmd
            text: Wright Map & TAM
          - file: example03.qmd
            text: Introducing the PP plot           
format:
  html:
    theme: flatly
