project:
  type: website
website:
  title: "WrightMap"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: Home
      - file: about.qmd
        text: About WrightMap
      - text: Tutorials      
        menu:
          - file: tutorial01.qmd
            text: Tutorial 01
          - file: tutorial02.qmd
            text: Tutorial 02
          - file: tutorial03.qmd
            text: Tutorial 03
          - file: tutorial04.qmd
            text: Tutorial 04
          - file: tutorial05.qmd
            text: Tutorial 05                          
          # Add more tutorials here

      - text: Examples
        menu:
          - file: example01.qmd
            text: Simulating data
          - file: example02.qmd
            text: Wright Map & TAM
          - file: example03.qmd
            text: Introducing the PP plot           
format:
  html:
    theme: flatly
