on:
  push:
    branches: main
  workflow_dispatch:

name: Quarto Publish

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install pak
        run: install.packages('pak')
        shell: Rscript {0}

      - name: Install dependencies using pak
        run: |
          pak::pkg_install(c("WrightMap", "knitr", "rmarkdown", "downlit", "xml2", "ggplot2", "psych", "QuantPsyc", "TeachingDemos", "rockchalk"))
        shell: Rscript {0}

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: website
  
      - name: Render and Deploy to Github Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: gh-pages
          path: website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
