on:
  push:
    branches: main
  workflow_dispatch:

name: Quarto Publish

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install Wrightmap
        run: install.packages("WrightMap")
        shell: Rscript {0}
        
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::rmarkdown
            any::TAM
            any::RColorBrewer

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: website
          to: html
  
      - name: Deploy to Github Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
